on: [push]
name: main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379/tcp

    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.14
      with:
        distribution: 'full'
        variant: 'CS'
        version: '8.4'

    - name: Install Package & Deps
      run: raco pkg install --auto --batch redis-lib/ redis-doc/ redis-test/ redis/

    - name: Run Tests
      run: raco test redis-lib/ redis-test/
      env:
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
