on: [push, pull_request]
name: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: docker://bogdanp/racket:7.3
      with:
        entrypoint: /github/workspace/ci/build.sh
    - name: test
      uses: docker://bogdanp/racket:7.3
      with:
        entrypoint: /github/workspace/ci/test.sh
    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
